language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: zwJ5RDcOV9MjJHPIoyWfRaqk+DT1HaKeGI8/7d/RBX37jSKVpzfgSvh60PVyhYRFoTpeS8b2A7c1kNUelWV7WzoTH2G+dtyrrJr6G5YCm3RUREjTvTu5URQvuLB8aUO1uJlgk0JYOrhm78iljqGCNUOzCWS5Ar7MapqE5sq/kYpTC10XjPJEpEmIwBY6EPuSj1U3NcNVc4XLEskyM7DhsNQ44bjo0kL+xDpxXaD/K2foSDwTwM9NQrUTHEygTLUJZGS5A62gFosdxcBjZV6KdXXN8F7xziHhZSE6ybjVv+TcSwGCYNmx0oCRcVHyZURD3Zj2biFhbK0vvgmGupvmm2Kg2+ysaQQNWJ2XH/x1GepsRmWCkgFdNX6u46JRt+tnEbKep1a/eWKJ9CDc+75nRx85kYEFkQfMCWMae7TH9pQmNmtlN7eipl+zAZ6JAeNUBzWdeUgI6mNAggczUVLbdhuZ7r0BGzEr6+uqw137yvj1WNftS7Y9zr6x3nI51DBg+jaovYkp8szK3aH2iPIyHQLdkwsg7zi7COLs5h+jb7jtShu/iaood4G4Qa5U2PQJrzrMl0f7YA60cpzgypZUQQSJkglPgrhQFr6MeRUwnmbuvRMIwCQD4TeYqJkkRjxzrfWag86Pc1BjSuZufb52e+3/2G9vPTCy+GJjRzmmwx8=
  app: pure-basin-53734
  on:
    repo: Jean-Luc19/node-shopping-list-integration-test
